name: CI

on:
  pull_request:
  push:
    tags: '*'
    branches-ignore:
      - 'renovate**'
    paths-ignore:
      - 'README.md'
      - 'renovate.json'
      - 'LICENSE'
      - '.github/**'
      - '.gitattributes'
      - 'dependabot.yml'

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Compute name
        run: |
          IMAGE_NAME=docker-jvm
          echo IMAGE_NAME="${IMAGE_NAME}"
          echo IMAGE_NAME="${IMAGE_NAME}" >> ${GITHUB_ENV}
      - name: Compute version
        run: |
          VERSION="$(git rev-list --all --count).$(date +%Y%m%d.%H%M)"
          echo VERSION="${VERSION}"
          echo VERSION="${VERSION}" >> ${GITHUB_ENV}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create version tag
        if: ${{ github.event_name != 'pull_request' }}
        uses: rickstaa/action-create-tag@v1.5.4
        with:
          tag: "${{ env.VERSION }}"
          message: "Release ${{ env.VERSION }}"
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
            "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
